/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Province, Attraction, Hotel, Activity, Vehicle, Review } from './types';

export const provinces: Province[] = [
  {
    id: 'quang-nam',
    name: 'Quảng Nam - Hội An',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    description: 'Thương cảng sầm uất thế kỷ XVII giữ gìn nguyên vẹn nét cổ kính rêu phong.',
    tagline: 'Phố cổ đèn lồng, di sản lung linh',
    active: true,
  },
  {
    id: 'da-nang',
    name: 'Đà Nẵng',
    image: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=800&q=80',
    description: 'Thành phố đáng sống bậc nhất Việt Nam với những cây cầu huyền thoại bắc qua sông Hàn.',
    tagline: 'Biển bạc Mỹ Khê, Ngũ Hành Sơn hùng vĩ',
    active: false,
  },
  {
    id: 'thua-thien-hue',
    name: 'Thừa Thiên Huế',
    image: 'https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?auto=format&fit=crop&w=800&q=80',
    description: 'Cố đô ngàn năm văn hiến nằm êm đềm bên dòng sông Hương thơ mộng, cổ kính uy nghiêm.',
    tagline: 'Cung điện uy nghiêm, nhã nhạc cung đình',
    active: false,
  },
  {
    id: 'binh-dinh',
    name: 'Bình Định',
    image: 'https://images.unsplash.com/photo-1621539250328-3e440939bc5d?auto=format&fit=crop&w=800&q=80',
    description: 'Vùng đất võ trời văn với những tháp Chăm cổ kính trầm mặc và bãi biển Kỳ Co ngọc bích.',
    tagline: 'Biển Kỳ Co, tháp Chăm ngàn năm',
    active: false,
  },
  {
    id: 'khanh-hoa',
    name: 'Khánh Hòa - Nha Trang',
    image: 'https://images.unsplash.com/photo-1584013321612-e8c107f27f1b?auto=format&fit=crop&w=800&q=80',
    description: 'Vịnh biển đẹp bậc nhất thế giới với dải cát trắng mịn màng và dừa xanh thơ mộng.',
    tagline: 'Vịnh Nha Trang, thiên đường rực rỡ',
    active: false,
  },
  {
    id: 'quang-binh',
    name: 'Quảng Bình',
    image: 'https://images.unsplash.com/photo-1618083707368-b3823daa2726?auto=format&fit=crop&w=800&q=80',
    description: 'Vương quốc hang động thế giới chứa đựng kiệt tác thiên nhiên Sơn Đoòng và Phong Nha kì vĩ.',
    tagline: 'Kỳ quan Sơn Đoòng, Phong Nha đệ nhất động',
    active: false,
  },
  {
    id: 'phu-yen',
    name: 'Phú Yên',
    image: 'https://images.unsplash.com/photo-1623161474966-2615a0c33fb3?auto=format&fit=crop&w=800&q=80',
    description: 'Vùng đất hoa vàng trên cỏ xanh yên bình với Gành Đá Đĩa kỳ vĩ kiến tạo triệu năm.',
    tagline: 'Xứ sở hoa vàng cỏ xanh, Gành Đá Đĩa độc bản',
    active: false,
  },
  {
    id: 'ninh-thuan',
    name: 'Ninh Thuận',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=80',
    description: 'Vùng đất của nắng, gió, vịnh biển Vĩnh Hy tuyệt sắc bên những đồi cát mênh mông.',
    tagline: 'Vịnh Vĩnh Hy trong xanh, tháp cổ Pô Klong Garai',
    active: false,
  },
  {
    id: 'quang-ngai',
    name: 'Quảng Ngãi',
    image: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&w=800&q=80',
    description: 'Quê hương của đảo tỏi Lý Sơn hoang sơ mộc mạc và những cánh đồng muối trắng ngập nắng.',
    tagline: 'Thiên đường biển đảo Lý Sơn, núi Ấn sông Trà',
    active: false,
  },
  {
    id: 'binh-thuan',
    name: 'Bình Thuận',
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80',
    description: 'Xứ sở cát đỏ Mũi Né lộng gió, dừa xanh nghiêng bóng bên dải sóng đại dương rực nắng.',
    tagline: 'Thủ phủ resort Mũi Né, đồi cát bay ngợp gió',
    active: false,
  },
  {
    id: 'quang-tri',
    name: 'Quảng Trị',
    image: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=800&q=80',
    description: 'Miền đất lịch sử anh hùng tự hào của vĩ tuyến 17 bên sông Bến Hải, cầu Hiền Lương.',
    tagline: 'Vĩ tuyến 17 hào hùng, thành cổ uy nghiêm',
    active: false,
  },
  {
    id: 'nghe-an',
    name: 'Nghệ An',
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deceeaf7?auto=format&fit=crop&w=800&q=80',
    description: 'Mảnh đất địa linh nhân kiệt với bãi biển Cửa Lò thơ mộng và những thảm hoa hướng dương rực rỡ.',
    tagline: 'Quê hương Sen nở thơm ngát, bãi biển Cửa Lò sóng biếc',
    active: false,
  }
];

export const attractionsByProvince: Record<string, Attraction[]> = {
  'quang-nam': [
    {
      id: 'hoian-oldtown',
      name: 'Phố cổ Hội An',
      image: 'https://images.unsplash.com/photo-1566837497217-1f912feab1fe?auto=format&fit=crop&w=600&q=80',
      description: 'Di sản văn hóa thế giới UNESCO bảo tồn hoàn hảo với hơn 1000 di tích cổ kính.',
      rating: 4.8,
      reviewsCount: '5.2k',
      lat: 15.8771,
      lng: 108.3267,
    },
    {
      id: 'chua-cau',
      name: 'Chùa Cầu',
      image: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&w=600&q=80',
      description: 'Biểu tượng lịch sử độc bản của Hội An giao thoa văn hóa Việt, Nhật và Hoa.',
      rating: 4.7,
      reviewsCount: '3.1k',
      lat: 15.8772,
      lng: 108.3258,
    },
    {
      id: 'thanh-ha-pottery',
      name: 'Làng gốm Thanh Hà',
      image: 'https://images.unsplash.com/photo-1596484552834-6a58bc238517?auto=format&fit=crop&w=600&q=80',
      description: 'Trải nghiệm làng nghề gốm truyền thống mộc mạc hơn 500 tuổi bên sông Thu Bồn.',
      rating: 4.6,
      reviewsCount: '579',
      lat: 15.8824,
      lng: 108.3006,
    },
    {
      id: 'an-bang-beach',
      name: 'Bãi biển An Bàng',
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
      description: 'Top bãi biển hoang sơ đẹp hàng đầu châu Á với bờ cát trắng mượt êm đềm.',
      rating: 4.9,
      reviewsCount: '1.8k',
      lat: 15.9126,
      lng: 108.3435,
    },
    {
      id: 'my-son-holyland',
      name: 'Thánh địa Mỹ Sơn',
      image: 'https://images.unsplash.com/photo-1596484552834-6a58bc238517?auto=format&fit=crop&w=600&q=80',
      description: 'Thành trì đền tháp Champa cổ kính ngàn năm tuổi nằm lọt thỏm giữa thung lũng xanh u tịch bí ẩn.',
      rating: 4.8,
      reviewsCount: '2.7k',
      lat: 15.7645,
      lng: 108.1235,
    },
    {
      id: 'cam-thanh-coconut',
      name: 'Rừng dừa Bảy Mẫu Cẩm Thanh',
      image: 'https://images.unsplash.com/photo-150752428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
      description: 'Trải nghiệm múa thúng chai độc đáo trên dòng nước rợp bóng dừa xanh rì rào đầy sôi động.',
      rating: 4.8,
      reviewsCount: '3.9k',
      lat: 15.8724,
      lng: 108.3685,
    },
    {
      id: 'tra-que-vegetable',
      name: 'Làng rau Trà Quế',
      image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=600&q=80',
      description: 'Hơn 300 năm tuổi gieo trồng các loại rau thơm hữu cơ nức tiếng bằng nguồn rong sông cổ ngọt ngào.',
      rating: 4.7,
      reviewsCount: '890',
      lat: 15.9015,
      lng: 108.3364,
    },
    {
      id: 'kim-bong-woodcarving',
      name: 'Làng mộc Kim Bồng',
      image: 'https://images.unsplash.com/photo-1596484552834-6a58bc238517?auto=format&fit=crop&w=600&q=80',
      description: 'Cơ sở mộc chạm khắc gỗ điêu luyện có lịch sử hơn 500 năm tuổi của các nghệ nhân tài hoa ven sông Hoài.',
      rating: 4.6,
      reviewsCount: '450',
      lat: 15.8652,
      lng: 108.3184,
    }
  ],
  'da-nang': [
    {
      id: 'dragon-bridge',
      name: 'Cầu Rồng Đà Nẵng',
      image: 'https://images.unsplash.com/photo-1559592443-7f87a79f6f82?auto=format&fit=crop&w=600&q=80',
      description: 'Biểu tượng thịnh vượng đầy kiêu hãnh của thành phố biển với màn trình diễn phun lửa nước ấn tượng cuối tuần.',
      rating: 4.9,
      reviewsCount: '8.4k',
      lat: 16.0612,
      lng: 108.2274,
    },
    {
      id: 'ba-na-hills',
      name: 'Bà Nà Hills & Cầu Vàng',
      image: 'https://images.unsplash.com/photo-1583244532610-2a234e7c3ecd?auto=format&fit=crop&w=600&q=80',
      description: 'Đường lên tiên cảnh với cây Cầu Vàng được nâng đỡ bởi đôi bàn tay khổng lồ bí ẩn.',
      rating: 4.8,
      reviewsCount: '12.3k',
      lat: 15.9986,
      lng: 107.9964,
    },
    {
      id: 'ngu-hanh-son',
      name: 'Danh thắng Ngũ Hành Sơn',
      image: 'https://images.unsplash.com/photo-1590372856149-e11154c5e315?auto=format&fit=crop&w=600&q=80',
      description: 'Năm ngọn núi đá vôi tâm linh huyền bí tạc nên những hang động Phật điện tráng lệ.',
      rating: 4.7,
      reviewsCount: '4.2k',
      lat: 16.0028,
      lng: 108.2635,
    },
    {
      id: 'son-tra-peninsula',
      name: 'Bán đảo Sơn Trà & Chùa Linh Ứng',
      image: 'https://images.unsplash.com/photo-1590372856149-e11154c5e315?auto=format&fit=crop&w=600&q=80',
      description: 'Lá phổi xanh của Đà Nẵng sở hữu tượng Phật Bà Quan Âm cao nhất Việt Nam 67m hướng thẳng biển khơi bao la.',
      rating: 4.9,
      reviewsCount: '9.2k',
      lat: 16.1025,
      lng: 108.2785,
    },
    {
      id: 'hai-van-pass',
      name: 'Đèo Hải Vân (Thiên hạ đệ nhất hùng quan)',
      image: 'https://images.unsplash.com/photo-1583244532610-2a234e7c3ecd?auto=format&fit=crop&w=600&q=80',
      description: 'Cung đèo hiểm trở kỳ vĩ uốn lượn sát bờ biển Thái Bình Dương thơ mộng mây phủ bồng bềnh.',
      rating: 4.9,
      reviewsCount: '6.1k',
      lat: 16.1956,
      lng: 108.1324,
    },
    {
      id: 'nam-o-reef',
      name: 'Rạn Nam Ô',
      image: 'https://images.unsplash.com/photo-1590372856149-e11154c5e315?auto=format&fit=crop&w=600&q=80',
      description: 'Bãi đá phủ rêu xanh ngọc bích tuyệt đẹp tựa cổ tích giữa vùng vịnh Đà Nẵng bình yên.',
      rating: 4.6,
      reviewsCount: '720',
      lat: 16.1082,
      lng: 108.1356,
    }
  ],
  'thua-thien-hue': [
    {
      id: 'hue-citadel',
      name: 'Đại Nội Huế',
      image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=600&q=80',
      description: 'Hoàng cung nguy nga tráng lệ chốn cấm thành của 13 vị vua triều đại nhà Nguyễn.',
      rating: 4.9,
      reviewsCount: '6.7k',
      lat: 16.4690,
      lng: 107.5786,
    },
    {
      id: 'khai-dinh-tomb',
      name: 'Lăng Khải Định',
      image: 'https://images.unsplash.com/photo-1596484552834-6a58bc238517?auto=format&fit=crop&w=600&q=80',
      description: 'Mẫu mực kiến trúc đỉnh cao kết hợp tinh hoa mỹ thuật Á-Âu khảm sành sứ độc nhất vô nhị.',
      rating: 4.8,
      reviewsCount: '2.5k',
      lat: 16.3986,
      lng: 107.5911,
    },
    {
      id: 'thien-mu-pagoda',
      name: 'Chùa Thiên Mụ',
      image: 'https://images.unsplash.com/photo-1590372856149-e11154c5e315?auto=format&fit=crop&w=600&q=80',
      description: 'Ngôi chùa cổ thiêng liêng nhất đất Thần Kinh soi bóng hiền hòa xuống dòng sông Hương.',
      rating: 4.7,
      reviewsCount: '1.9k',
      lat: 16.4528,
      lng: 107.5379,
    },
    {
      id: 'tu-duc-tomb',
      name: 'Lăng Tự Đức',
      image: 'https://images.unsplash.com/photo-1596484552834-6a58bc238517?auto=format&fit=crop&w=600&q=80',
      description: 'Tuyệt tác lăng tẩm thơ mộng nhất của triều Nguyễn với hồ nước, rặng thông và thi quán tao nhã thanh nhã.',
      rating: 4.8,
      reviewsCount: '3.1k',
      lat: 16.4328,
      lng: 107.5684,
    },
    {
      id: 'minh-mang-tomb',
      name: 'Lăng Minh Mạng',
      image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=600&q=80',
      description: 'Sự kết hợp hoàn hảo giữa kiến trúc hoàng cung uy nghiêm và phong cảnh thiên nhiên hữu tình sông núi hòa quyện.',
      rating: 4.9,
      reviewsCount: '2.8k',
      lat: 16.3885,
      lng: 107.5724,
    },
    {
      id: 'dong-ba-market',
      name: 'Chợ Đông Ba',
      image: 'https://images.unsplash.com/photo-1590372856149-e11154c5e315?auto=format&fit=crop&w=600&q=80',
      description: 'Khu chợ truyền thống lâu đời sầm uất nhất Huế, thiên đường ẩm thực và mua sắm quà lưu niệm địa phương.',
      rating: 4.6,
      reviewsCount: '4.5k',
      lat: 16.4712,
      lng: 107.5945,
    }
  ],
  'binh-dinh': [
    {
      id: 'eo-gio',
      name: 'Eo Gió Quy Nhơn',
      image: 'https://images.unsplash.com/photo-1583244532610-2a234e7c3ecd?auto=format&fit=crop&w=600&q=80',
      description: 'Eo biển lộng gió hoang sơ đẹp nhất Quy Nhơn ôm trọn làn nước xanh màu ngọc bích.',
      rating: 4.9,
      reviewsCount: '3.4k',
      lat: 13.7594,
      lng: 109.2192,
    },
    {
      id: 'ky-co',
      name: 'Bãi biển Kỳ Co',
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
      description: 'Thiên đường biển xanh cát trắng nắng vàng rực rỡ được mệnh danh là Maldives của Việt Nam.',
      rating: 4.8,
      reviewsCount: '2.9k',
      lat: 13.7656,
      lng: 109.2312,
    },
    {
      id: 'thap-banh-it',
      name: 'Tháp Bánh Ít',
      image: 'https://images.unsplash.com/photo-1590372856149-e11154c5e315?auto=format&fit=crop&w=600&q=80',
      description: 'Cụm tháp Chăm cổ kính hơn 1000 năm tuổi ghi dấu tinh hoa kiến trúc điêu khắc Chăm Pa độc đáo.',
      rating: 4.7,
      reviewsCount: '920',
      lat: 13.8328,
      lng: 109.1356,
    }
  ],
  'khanh-hoa': [
    {
      id: 'vinwonders-nha-trang',
      name: 'VinWonders Nha Trang',
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
      description: 'Công viên giải trí đẳng cấp thế giới tọa lạc trên đảo Hòn Tre với hệ thống cáp treo vượt biển tuyệt vời.',
      rating: 4.9,
      reviewsCount: '8.7k',
      lat: 12.2194,
      lng: 109.2435,
    },
    {
      id: 'thap-ba-ponagar',
      name: 'Tháp Bà Ponagar',
      image: 'https://images.unsplash.com/photo-1590372856149-e11154c5e315?auto=format&fit=crop&w=600&q=80',
      description: 'Quần thể kiến trúc đền tháp Chăm cổ kính linh thiêng ngự trị trên ngọn đồi nhỏ ven sông Cái.',
      rating: 4.8,
      reviewsCount: '4.1k',
      lat: 12.2654,
      lng: 109.1956,
    },
    {
      id: 'hon-chong',
      name: 'Danh thắng Hòn Chồng',
      image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=600&q=80',
      description: 'Quần thể đá tự nhiên xếp chồng lên nhau tạo nên cảnh quan kỳ thú hướng ra biển Nha Trang xanh thẳm.',
      rating: 4.7,
      reviewsCount: '1.8k',
      lat: 12.2721,
      lng: 109.2054,
    }
  ]
};

export const hotelsByProvince: Record<string, Hotel[]> = {
  'quang-nam': [
    {
      id: 'allegro-hoian',
      name: 'Allegro Hoi An Luxury Hotel & Spa',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '1.2k',
      pricePerNight: 1250000,
      description: 'Khách sạn 5 sao mang phong thái hoài cổ tao nhã ngay trung tâm phố cổ.',
      lat: 15.8778,
      lng: 108.3225,
    },
    {
      id: 'lasiesta-hoian',
      name: 'La Siesta Hoi An Resort & Spa',
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '2.4k',
      pricePerNight: 2120000,
      description: 'Khu nghỉ dưỡng sang trọng bậc nhất tựa ốc đảo xanh thơ mộng.',
      lat: 15.8821,
      lng: 108.3182,
    },
    {
      id: 'hoian-central-boutique',
      name: 'Hoi An Central Boutique Hotel',
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviewsCount: '430',
      pricePerNight: 860000,
      description: 'Phong cách thuộc địa Pháp kết hợp nét quyến rũ đặc trưng Á Đông cổ điển.',
      lat: 15.8790,
      lng: 108.3245,
    },
    {
      id: 'an-bang-hideaway',
      name: 'An Bang Beach Hideaway Homestay',
      image: 'https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviewsCount: '127',
      pricePerNight: 1350000,
      description: 'Homestay mộc mạc ẩn hiện giữa rặng dừa xanh mướt sát bờ biển thắm lộng gió.',
      lat: 15.9142,
      lng: 108.3421,
    },
    {
      id: 'anantara-hoian',
      name: 'Anantara Hoi An Resort',
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '840',
      pricePerNight: 3500000,
      description: 'Bên bờ sông Thu Bồn thơ mộng, mang phong cách kiến trúc Pháp-Việt tinh tế.',
      lat: 15.8775,
      lng: 108.3341,
    },
    {
      id: 'mulberry-collection-silk-eco',
      name: 'Mulberry Collection Silk Eco',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviewsCount: '680',
      pricePerNight: 950000,
      description: 'Khách sạn sinh thái xanh mát mang đậm hơi thở kiến trúc tre trúc mộc mạc Hội An, gần gũi thiên nhiên.',
      lat: 15.8795,
      lng: 108.3214,
    },
    {
      id: 'belmar-resort-spa',
      name: 'Bel Marina Hoi An Resort',
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '1.5k',
      pricePerNight: 1850000,
      description: 'Khu nghỉ dưỡng 5 sao sang trọng nằm sát sông Thu Bồn, nơi ngắm cảnh hoàng hôn sông Hoài mộng mơ đẹp nhất.',
      lat: 15.8745,
      lng: 108.3248,
    },
    {
      id: 'little-riverside-hoian',
      name: 'Little Riverside Hoi An Luxury Hotel',
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '520',
      pricePerNight: 2300000,
      description: 'Khách sạn boutique quý phái cổ điển Pháp kết hợp những mảng xanh thanh tịnh êm đềm bên dòng sông.',
      lat: 15.8784,
      lng: 108.3375,
    }
  ],
  'da-nang': [
    {
      id: 'intercon-danang',
      name: 'InterContinental Danang Sun Peninsula Resort',
      image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=600&q=80',
      rating: 5.0,
      reviewsCount: '3.1k',
      pricePerNight: 8500000,
      description: 'Tuyệt tác nghỉ dưỡng huyền thoại nép mình bên bán đảo Sơn Trà hoang sơ.',
      lat: 16.1218,
      lng: 108.3075,
    },
    {
      id: 'tiamo-danang',
      name: 'Tiamo Sea View Hotel Danang',
      image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviewsCount: '810',
      pricePerNight: 950000,
      description: 'Tận hưởng gió biển Mỹ Khê tươi mát ngập tràn từ ban công rực nắng.',
      lat: 16.0694,
      lng: 108.2464,
    },
    {
      id: 'pullman-danang',
      name: 'Pullman Danang Beach Resort',
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviewsCount: '1.4k',
      pricePerNight: 2450000,
      description: 'Khu nghỉ dưỡng sang trọng bên bãi biển Bắc Mỹ An với hồ bơi vô cực ấn tượng.',
      lat: 16.0425,
      lng: 108.2512,
    },
    {
      id: 'novotel-danang',
      name: 'Novotel Danang Premier Han River',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviewsCount: '2.1k',
      pricePerNight: 1950000,
      description: 'Tòa tháp biểu tượng nhìn ra sông Hàn, có Sky bar 36 cao nhất Đà Nẵng náo nhiệt.',
      lat: 16.0782,
      lng: 108.2235,
    },
    {
      id: 'shilla-danang',
      name: 'Shilla Monogram Quangnam Danang',
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '980',
      pricePerNight: 3100000,
      description: 'Lối sống tinh tế giao hòa Hàn - Việt, sở hữu hồ bơi vô cực bốn mùa lộng gió.',
      lat: 15.9682,
      lng: 108.2891,
    },
    {
      id: 'salene-beach-danang',
      name: 'Sala Danang Beach Hotel',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviewsCount: '1.1k',
      pricePerNight: 1200000,
      description: 'Khách sạn sát biển Mỹ Khê với hồ bơi vô cực trên tầng thượng ngắm trọn vẹn vịnh biển xanh mát trong lành.',
      lat: 16.0685,
      lng: 108.2465,
    },
    {
      id: 'haian-beach-hotel',
      name: 'Haian Beach Hotel & Spa',
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviewsCount: '2.3k',
      pricePerNight: 1450000,
      description: 'Ốc đảo nghỉ dưỡng biển hiện đại sầm uất bậc nhất, phục vụ trà chiều và khay thức ăn nổi hấp dẫn tại hồ bơi.',
      lat: 16.0595,
      lng: 108.2478,
    },
    {
      id: 'radisson-danang',
      name: 'Radisson Hotel Danang',
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '890',
      pricePerNight: 2200000,
      description: 'Khách sạn đẳng cấp quốc tế tọa lạc đắc địa trên cung đường Võ Nguyên Giáp, mở rộng tầm nhìn vô cực ra đại dương.',
      lat: 16.0712,
      lng: 108.2458,
    }
  ],
  'thua-thien-hue': [
    {
      id: 'silkpath-hue',
      name: 'Silk Path Grand Hue Hotel',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '1.5k',
      pricePerNight: 1650000,
      description: 'Khách sạn tráng lệ phong cách tân cổ điển hoàng gia Pháp quý phái.',
      lat: 16.4611,
      lng: 107.5855,
    },
    {
      id: 'alba-spring',
      name: 'Alba Wellness Valley by Fusion',
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '920',
      pricePerNight: 3200000,
      description: 'Nghỉ dưỡng suối khoáng nóng thiền tịnh, trị liệu toàn diện tâm thân trí sâu sắc.',
      lat: 16.5412,
      lng: 107.4589,
    },
    {
      id: 'azerai-la-residence',
      name: 'Azerai La Residence Hue',
      image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '620',
      pricePerNight: 4100000,
      description: 'Dinh thự cổ phong cách Art Deco nằm duyên dáng bên bờ sông Hương lộng gió.',
      lat: 16.4631,
      lng: 107.5812,
    },
    {
      id: 'indochine-palace-hue',
      name: 'Imperial Indochine Palace Hue',
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviewsCount: '1.1k',
      pricePerNight: 1400000,
      description: 'Phong cách Đông Dương sang trọng quý phái nổi bật giữa lòng phố cổ Huế trầm mặc.',
      lat: 16.4582,
      lng: 107.5934,
    },
    {
      id: 'senna-hue',
      name: 'Senna Hue Hotel Boutique',
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviewsCount: '340',
      pricePerNight: 1100000,
      description: 'Mái ngói đỏ và khu vườn trung tâm yên bình giao hòa văn hóa lịch sử triều Nguyễn.',
      lat: 16.4645,
      lng: 107.5898,
    },
    {
      id: 'banyan-tree-langco',
      name: 'Banyan Tree Lăng Cô',
      image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=600&q=80',
      rating: 5.0,
      reviewsCount: '450',
      pricePerNight: 9500000,
      description: 'Khu nghỉ dưỡng biệt thự có hồ bơi riêng tư sang trọng bậc nhất, tựa lưng vào dãy Trường Sơn hùng vĩ hướng thẳng vịnh Lăng Cô.',
      lat: 16.2734,
      lng: 107.9545,
    },
    {
      id: 'pilgrimage-village',
      name: 'Pilgrimage Village Resort & Spa',
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '870',
      pricePerNight: 1800000,
      description: 'Làng hành hương mộc mạc yên tịnh chốn thôn dã, mang phong cách nhà rường cổ kết hợp liệu pháp thiền trị liệu spa sâu sắc.',
      lat: 16.4252,
      lng: 107.5982,
    }
  ],
  'binh-dinh': [
    {
      id: 'anya-premier-quy-nhon',
      name: 'Anya Premier Hotel Quy Nhơn',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviewsCount: '580',
      pricePerNight: 1450000,
      description: 'Khách sạn 5 sao sang trọng ngay trung tâm thành phố biển, phòng có view trọn vịnh biển.',
      lat: 13.7584,
      lng: 109.2156,
    },
    {
      id: 'crown-retreat',
      name: 'Crown Retreat Quy Nhơn Resort',
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '390',
      pricePerNight: 2800000,
      description: 'Khu nghỉ dưỡng bungalow cao cấp nép mình bên sườn đồi hướng thẳng ra bãi biển Cát Tiến hoang sơ.',
      lat: 13.9124,
      lng: 109.2564,
    },
    {
      id: 'avani-quy-nhon',
      name: 'Avani Quy Nhon Resort & Spa',
      image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '810',
      pricePerNight: 3200000,
      description: 'Ốc đảo nhiệt đới hoang sơ với bãi cát riêng, thích hợp lặn san hô và thư giãn yoga.',
      lat: 13.6892,
      lng: 109.2241,
    },
    {
      id: 'fleur-de-lys-quynhon',
      name: 'Fleur de Lys Hotel Quy Nhon',
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviewsCount: '412',
      pricePerNight: 1300000,
      description: 'Tiêu chuẩn 4 sao quốc tế quyến rũ, nằm đối diện bãi biển Quy Nhơn hiền hòa rợp bóng dừa.',
      lat: 13.7595,
      lng: 109.2175,
    },
    {
      id: 'seagull-hotel-quynhon',
      name: 'Seagull Hải Âu Hotel Quy Nhon',
      image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=600&q=80',
      rating: 4.6,
      reviewsCount: '520',
      pricePerNight: 850000,
      description: 'Khách sạn có ban công sát biển độc đáo, nghe sóng vỗ rì rào lãng mạn lộng gió đêm.',
      lat: 13.7541,
      lng: 109.2144,
    }
  ],
  'khanh-hoa': [
    {
      id: 'amiana-resort',
      name: 'Amiana Resort Nha Trang',
      image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '2.8k',
      pricePerNight: 3900000,
      description: 'Khu nghỉ dưỡng 5 sao sang trọng sở hữu hồ bơi nước biển tự nhiên khổng lồ rộng 2.500m2.',
      lat: 12.3012,
      lng: 109.2156,
    },
    {
      id: 'sheraton-nha-trang',
      name: 'Sheraton Nha Trang Hotel & Spa',
      image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviewsCount: '1.9k',
      pricePerNight: 2100000,
      description: 'Tọa lạc trên đường Trần Phú sầm uất với tất cả các phòng đều sở hữu ban công ngắm toàn cảnh vịnh biển.',
      lat: 12.2494,
      lng: 109.1964,
    },
    {
      id: 'six-senses-ninh-van',
      name: 'Six Taxes Ninh Van Bay Luxury Resort',
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80',
      rating: 5.0,
      reviewsCount: '1.2k',
      pricePerNight: 9800000,
      description: 'Biệt thự gỗ mộc mạc nép mình bên những tảng đá khổng lồ hoang dã vịnh Ninh Vân biệt lập.',
      lat: 12.3582,
      lng: 109.2741,
    },
    {
      id: 'intercon-nhatrang',
      name: 'InterContinental Nha Trang Hotel',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '1.7k',
      pricePerNight: 2800000,
      description: 'Nghỉ dưỡng thượng lưu phong cách đương đại ngay trung tâm đại lộ Trần Phú rực rỡ.',
      lat: 12.2452,
      lng: 109.1978,
    },
    {
      id: 'vinpearl-luxury-nhatrang',
      name: 'Vinpearl Luxury Nha Trang',
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviewsCount: '890',
      pricePerNight: 4500000,
      description: 'Biệt thự sang trọng cổ điển biệt lập nằm an bình giữa khu vườn nhiệt đới xanh rì rào.',
      lat: 12.2185,
      lng: 109.2451,
    }
  ]
};

export const activitiesByProvince: Record<string, Activity[]> = {
  'quang-nam': [
    {
      id: 'act-town-tour',
      name: 'Tour tham quan di sản Phố Cổ Hội An',
      image: 'https://images.unsplash.com/photo-1566837497217-1f912feab1fe?auto=format&fit=crop&w=600&q=80',
      price: 150000,
      description: 'Đi bộ khám phá các hội quán lừng danh, giếng cổ Bá Lễ, và thưởng thức nghệ thuật hát Bài Chòi cổ truyền.',
      rating: 4.8,
      reviewsCount: '920',
      lat: 15.8771,
      lng: 108.3267,
    },
    {
      id: 'act-hoai-lantern',
      name: 'Trải Nghiệm Thả Đèn Hoa Đăng Sông Hoài',
      image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=600&q=80',
      price: 100000,
      description: 'Du ngoạn bằng thuyền gỗ trên dòng sông Hoài thơ mộng và gửi ước nguyện lãng mạn qua cánh đèn đăng.',
      rating: 4.9,
      reviewsCount: '2.5k',
      lat: 15.8752,
      lng: 108.3275,
    },
    {
      id: 'act-cooking-class',
      name: 'Lớp Học Nấu Ăn Đặc Sản Hội An',
      image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=600&q=80',
      price: 500000,
      description: 'Đi đò đến chợ địa phương mua nguyên liệu tươi và học chế biến Mì Quảng, Bánh Xèo, Cao Lầu chính hiệu.',
      rating: 4.8,
      reviewsCount: '650',
      lat: 15.8812,
      lng: 108.3315,
    },
    {
      id: 'act-rustic-bike',
      name: 'Tour Đạp Xe Trải Nghiệm Làng Quê Cẩm Kim',
      image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=600&q=80',
      price: 250000,
      description: 'Thong thả lướt xe dạo qua luống cói rợp bóng dừa xanh, trải nghiệm làm bánh tráng xắt nung.',
      rating: 4.7,
      reviewsCount: '340',
      lat: 15.8624,
      lng: 108.3125,
    },
    {
      id: 'act-cham-island',
      name: 'Lặn Ngắm San Hô Cù Lao Chàm Bằng Cano Cao Tốc',
      image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
      price: 650000,
      description: 'Cano cao tốc đưa bạn bơi ngụp giữa làn khói nước thủy tinh, thưởng ngoạn đại dương đảo xanh bí ẩn.',
      rating: 4.9,
      reviewsCount: '1.4k',
      lat: 15.9328,
      lng: 108.5132,
    },
    {
      id: 'act-thung-chai-camthanh',
      name: 'Tour thuyền thúng rừng dừa Bảy Mẫu Cẩm Thanh',
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
      price: 150000,
      description: 'Ngồi thúng chai lướt sóng nước lộng gió, xem các nghệ nhân múa thúng xoay vòng tròn điêu luyện đầy kích tính, học cách giăng lưới bắt cá sông cổ truyền.',
      rating: 4.8,
      reviewsCount: '1.9k',
      lat: 15.8724,
      lng: 108.3685,
    },
    {
      id: 'act-myson-sunrise',
      name: 'Tour đón bình minh Thánh địa Mỹ Sơn cổ kính',
      image: 'https://images.unsplash.com/photo-1596484552834-6a58bc238517?auto=format&fit=crop&w=600&q=80',
      price: 350000,
      description: 'Khởi hành sớm đón nhận những vệt bình minh ấm áp đầu tiên chiếu rọi qua các đền tháp gạch Champa u tịch trầm mặc, thưởng thức điệu nhảy múa Apsara say đắm thần tiên.',
      rating: 4.9,
      reviewsCount: '780',
      lat: 15.7645,
      lng: 108.1235,
    },
    {
      id: 'act-hoian-lantern-making',
      name: 'Lớp học tự tay làm đèn lồng lụa Hội An truyền thống',
      image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=600&q=80',
      price: 120000,
      description: 'Được các nghệ nhân bản địa lâu năm cầm tay chỉ việc tạo khung tre uốn nắn tinh xảo, dán vải lụa Hà Đông cao cấp rực rỡ sắc màu làm món quà kỷ niệm ý nghĩa sâu sắc.',
      rating: 4.7,
      reviewsCount: '430',
      lat: 15.8785,
      lng: 108.3284,
    },
    {
      id: 'act-hoian-food-walking',
      name: 'Tour đi bộ thưởng thức tinh hoa ẩm thực đường phố Hội An',
      image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=600&q=80',
      price: 290000,
      description: 'Dạo bước cùng hướng dẫn viên bản xứ len lỏi sâu vào ngõ nhỏ rêu phong ăn sập các món ngon nức tiếng: bánh mì Phượng giòn rụm béo pate, cao lầu Bá Lễ dai sần sật, bánh bao bánh vạc tinh tế và ly nước Mót thảo mộc sảng khoái.',
      rating: 4.9,
      reviewsCount: '1.5k',
      lat: 15.8771,
      lng: 108.3267,
    }
  ],
  'da-nang': [
    {
      id: 'act-han-river-cruise',
      name: 'Du thuyền Ngắm Sông Hàn lung linh về đêm',
      image: 'https://images.unsplash.com/photo-1559592443-7f87a79f6f82?auto=format&fit=crop&w=600&q=80',
      price: 150000,
      description: 'Thoải mái uống nước dừa, múa Chăm lộng lẫy và chiêm ngưỡng các cây cầu lấp lánh trong màn sương rực rỡ.',
      rating: 4.8,
      reviewsCount: '1.2k',
      lat: 16.0612,
      lng: 108.2274,
    },
    {
      id: 'act-banahills-ticket',
      name: 'Vé Cáp Treo Trọn Gói Bà Nà Hills',
      image: 'https://images.unsplash.com/photo-1583244532610-2a234e7c3ecd?auto=format&fit=crop&w=600&q=80',
      price: 900000,
      description: 'Chinh phục cáp treo đạt kỷ lục thế giới thưởng ngoạn công viên chủ đề Fantasy, Làng Pháp cổ xưa.',
      rating: 4.9,
      reviewsCount: '5.8k',
      lat: 15.9986,
      lng: 107.9964,
    },
    {
      id: 'act-marble-mountain',
      name: 'Khám phá Động Huyền Không - Ngũ Hành Sơn',
      image: 'https://images.unsplash.com/photo-1590372856149-e11154c5e315?auto=format&fit=crop&w=600&q=80',
      price: 80000,
      description: 'Hành trình tâm linh leo núi Ngũ Hành dạo quanh quần thể chùa Tam Thai, Linh Ứng kỳ vĩ với hướng dẫn viên.',
      rating: 4.8,
      reviewsCount: '950',
      lat: 16.0028,
      lng: 108.2635,
    },
    {
      id: 'act-sontra-sunset',
      name: 'Ngắm Hoàng Hôn Bán Đảo Sơn Trà & Chùa Linh Ứng',
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=600&q=80',
      price: 320000,
      description: 'Chiêm bái tượng Phật Bà cao 67m uy nghiêm hướng biển, săn ảnh hoàng hôn lãng mạn lộng gió.',
      rating: 4.9,
      reviewsCount: '1.1k',
      lat: 16.1008,
      lng: 108.2778,
    },
    {
      id: 'act-paragliding-sontra',
      name: 'Trải Nghiệm Bay Dù Lượn Đỉnh Bàn Cờ Sơn Trà',
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
      price: 1850000,
      description: 'Bay dù lượn cùng phi công chuyên nghiệp chiêm ngưỡng toàn bộ eo biển Đà Nẵng tuyệt đẹp từ tầng mây.',
      rating: 4.9,
      reviewsCount: '180',
      lat: 16.1212,
      lng: 108.2934,
    },
    {
      id: 'act-sontra-snorkeling',
      name: 'Tour lặn biển ngắm san hô Bán đảo Sơn Trà',
      image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
      price: 450000,
      description: 'Cano siêu tốc đưa bạn vi vu bến Nam lặn ngắm rạn san hô tự nhiên tuyệt mỹ, bơi lội mát lạnh và thưởng thức bữa trưa hải sản tươi sống chất lượng cao.',
      rating: 4.8,
      reviewsCount: '890',
      lat: 16.1025,
      lng: 108.2785,
    },
    {
      id: 'act-nui-than-tai',
      name: 'Vé trọn gói Công viên suối khoáng nóng Núi Thần Tài',
      image: 'https://images.unsplash.com/photo-1590372856149-e11154c5e315?auto=format&fit=crop&w=600&q=80',
      price: 450000,
      description: 'Trải nghiệm ngâm suối nước nóng Onsen kiểu Nhật, tắm bùn khoáng tinh khiết phục hồi thể lực và thỏa sức vui chơi công viên nước đầy phấn khích.',
      rating: 4.8,
      reviewsCount: '2.1k',
      lat: 15.9812,
      lng: 107.9542,
    }
  ],
  'thua-thien-hue': [
    {
      id: 'act-hue-perfume-river',
      name: 'Nghe ca Huế trên thuyền Rồng sông Hương nửa đêm',
      image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=600&q=80',
      price: 180000,
      description: 'Thả hồn vào điệu hò Huế mộc mạc âm vang tao nhã quyện làn nhang trầm dìu dặt cổ truyền.',
      rating: 4.8,
      reviewsCount: '840',
      lat: 16.4690,
      lng: 107.5786,
    },
    {
      id: 'act-hue-food-tour',
      name: 'Food Tour Xích Lô Huế Về Đêm',
      image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=600&q=80',
      price: 350000,
      description: 'Trải nghiệm xích lô dạo đêm cố đô thưởng thức bánh bèo, nậm, lọc, bún bò Huế và chè hẻm 20 món trứ danh.',
      rating: 4.9,
      reviewsCount: '730',
      lat: 16.4654,
      lng: 107.5912,
    },
    {
      id: 'act-imperial-citadel',
      name: 'Tham Quan Đại Nội Huế Có Thuyết Minh Viên',
      image: 'https://images.unsplash.com/photo-1590372856149-e11154c5e315?auto=format&fit=crop&w=600&q=80',
      price: 250000,
      description: 'Khám phá chốn hoàng cung triều Nguyễn cổ kính, nghe thuyết minh về lịch sử thăng trầm của 13 triều vua.',
      rating: 4.8,
      reviewsCount: '1.6k',
      lat: 16.4692,
      lng: 107.5771,
    },
    {
      id: 'act-tu-duc-tomb',
      name: 'Hành Trình Khám Phá Lăng Tự Đức & Khải Định',
      image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=600&q=80',
      price: 380000,
      description: 'Chiêm ngưỡng hai công trình kiến trúc lăng tẩm hoàng gia độc đáo pha trộn văn hóa Tây phương sắc sảo.',
      rating: 4.9,
      reviewsCount: '950',
      lat: 16.4328,
      lng: 107.5672,
    },
    {
      id: 'act-incense-village',
      name: 'Lớp Học Làm Hương Thảo Mộc Làng Thủy Xuân',
      image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=600&q=80',
      price: 150000,
      description: 'Trải nghiệm se hương thủ công rực rỡ sắc màu, lưu lại bức ảnh check-in tuyệt đẹp đậm chất thơ.',
      rating: 4.8,
      reviewsCount: '412',
      lat: 16.4512,
      lng: 107.5589,
    },
    {
      id: 'act-hue-royal-dinner',
      name: 'Trải nghiệm yến tiệc hoàng cung Triều Nguyễn',
      image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=600&q=80',
      price: 1200000,
      description: 'Hóa thân thành vua chúa, phi tần triều Nguyễn thưởng thức thực đơn ngự thiện cung đình được trang trí công phu, lắng nghe nhã nhạc cung đình Huế quý phái.',
      rating: 4.9,
      reviewsCount: '350',
      lat: 16.4690,
      lng: 107.5786,
    },
    {
      id: 'act-hue-cycling-village',
      name: 'Tour đạp xe dạo quanh làng cổ Thủy Biều mộc mạc',
      image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=600&q=80',
      price: 250000,
      description: 'Đạp xe nhẹ nhàng dưới những rặng cây thanh trà xum xuê trĩu quả, ngâm chân thảo mộc thảo dược thư giãn và tự học làm mứt bưởi thanh tao đặc sản truyền thống.',
      rating: 4.7,
      reviewsCount: '410',
      lat: 16.4354,
      lng: 107.5412,
    }
  ],
  'binh-dinh': [
    {
      id: 'act-ky-co-coral',
      name: 'Tour Cano Kỳ Co - lặn ngắm san hô Bãi Dứa Quy Nhơn',
      image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
      price: 450000,
      description: 'Cano siêu tốc đưa bạn ra bãi biển Kỳ Co tắm biển, chơi phao chuối và ngắm san hô lộng lẫy tại Bãi Dứa Quy Nhơn.',
      rating: 4.9,
      reviewsCount: '1.2k',
      lat: 13.7656,
      lng: 109.2312,
    },
    {
      id: 'act-eo-gio-trek',
      name: 'Check-in Kỳ Quan Eo Gió & Tịnh Xá Ngọc Hòa',
      image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=600&q=80',
      price: 120000,
      description: 'Chinh phục con đường đi bộ ven vách núi ôm trọn biển khơi lộng gió và chiêm bái tượng Phật đôi cao nhất Việt Nam.',
      rating: 4.8,
      reviewsCount: '810',
      lat: 13.7612,
      lng: 109.2452,
    },
    {
      id: 'act-cham-towers-tour',
      name: 'Tour Khảo Cổ Tháp Chăm Bánh Ít & Tháp Đôi Quy Nhơn',
      image: 'https://images.unsplash.com/photo-1590372856149-e11154c5e315?auto=format&fit=crop&w=600&q=80',
      price: 290000,
      description: 'Tham quan những ngọn tháp gạch đỏ nghìn năm tuổi rực rỡ, nghe thuyết minh về vương quốc Champa bí ẩn.',
      rating: 4.7,
      reviewsCount: '210',
      lat: 13.8124,
      lng: 109.1564,
    },
    {
      id: 'act-haitu-sunrise',
      name: 'Săn Bình Minh Hải Đăng Mũi Điện Quy Nhơn',
      image: 'https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?auto=format&fit=crop&w=600&q=80',
      price: 350000,
      description: 'Chào đón ánh bình minh tuyệt diệu đầu tiên của tổ quốc từ ngọn hải đăng sừng sững sương sớm.',
      rating: 4.9,
      reviewsCount: '140',
      lat: 13.5891,
      lng: 109.2892,
    },
    {
      id: 'act-quynhon-food',
      name: 'Food Tour Thưởng Thức Hải Sản Quy Nhơn Về Đêm',
      image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=600&q=80',
      price: 400000,
      description: 'Thỏa thích nếm bánh xèo tôm nhảy, lẩu sứa nước lèo, ốc len xào dừa, chả ram tôm đất giòn rụm.',
      rating: 4.8,
      reviewsCount: '530',
      lat: 13.7582,
      lng: 109.2198,
    }
  ],
  'khanh-hoa': [
    {
      id: 'act-four-islands',
      name: 'Tour Cano 3 Đảo VIP Vịnh Nha Trang',
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
      price: 550000,
      description: 'Du ngoạn Vịnh Nha Trang bằng cano cao tốc, tắm biển rạn san hô Hòn Mun, bơi lội và ăn trưa hải sản tươi.',
      rating: 4.9,
      reviewsCount: '2.5k',
      lat: 12.2194,
      lng: 109.2435,
    },
    {
      id: 'act-mud-bath',
      name: 'Tắm Bùn Khoáng Nóng Trị Liệu Tháp Bà Nha Trang',
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=600&q=80',
      price: 300000,
      description: 'Thư giãn ngâm bùn khoáng nóng thiên nhiên giàu dưỡng chất và tắm hồ bơi hydrotherapy sảng khoái.',
      rating: 4.8,
      reviewsCount: '1.9k',
      lat: 12.2682,
      lng: 109.1956,
    },
    {
      id: 'act-sunset-yacht',
      name: 'Du Thuyền Thượng Lưu Hoàng Hôn Ngắm Vịnh Nha Trang',
      image: 'https://images.unsplash.com/photo-1559592443-7f87a79f6f82?auto=format&fit=crop&w=600&q=80',
      price: 1250000,
      description: 'Thưởng thức nhạc violin lãng mạn cùng tiệc cocktail canape hảo hạng khi hoàng hôn buông xuống vịnh biển.',
      rating: 4.9,
      reviewsCount: '340',
      lat: 12.2152,
      lng: 109.2412,
    },
    {
      id: 'act-diving-mun-island',
      name: 'Trải Nghiệm Lặn Bình Khí Khám Phá Rạn San Hô Hòn Mun',
      image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
      price: 850000,
      description: 'Lặn sâu ngắm vương quốc san hô đa sắc màu cùng huấn luyện viên quốc tế chuyên nghiệp chu đáo.',
      rating: 4.9,
      reviewsCount: '620',
      lat: 12.1894,
      lng: 109.2635,
    },
    {
      id: 'act-kong-forest',
      name: 'Vui Chơi Zipline Chinh Phục Kong Forest Nha Trang',
      image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=600&q=80',
      price: 950000,
      description: 'Bay giữa tán rừng nhiệt đới bạt ngàn với hệ thống zipline xuyên rừng đạt chuẩn quốc tế an toàn.',
      rating: 4.8,
      reviewsCount: '280',
      lat: 12.1524,
      lng: 108.9856,
    }
  ],
  'quang-binh': [
    {
      id: 'act-phong-nha-cave',
      name: 'Khám phá Động Phong Nha Kỳ Vĩ bằng thuyền gỗ',
      image: 'https://images.unsplash.com/photo-1618083707368-b3823daa2726?auto=format&fit=crop&w=600&q=80',
      price: 150000,
      description: 'Ngồi thuyền độc mộc xuôi dòng sông Son vào lòng hang động nước dài nhất Thế giới, chiêm ngưỡng thạch nhũ triệu năm.',
      rating: 4.9,
      reviewsCount: '1.8k',
      lat: 17.5824,
      lng: 106.2854,
    },
    {
      id: 'act-thien-duong-cave',
      name: 'Chinh phục Động Thiên Đường - Hoàng cung trong lòng đất',
      image: 'https://images.unsplash.com/photo-1590372856149-e11154c5e315?auto=format&fit=crop&w=600&q=80',
      price: 250000,
      description: 'Khám phá cây cầu gỗ dài nhất trong hang động Việt Nam, chiêm ngưỡng tuyệt tác thạch nhũ tráng lệ huyền ảo.',
      rating: 4.9,
      reviewsCount: '1.4k',
      lat: 17.5214,
      lng: 106.2235,
    },
    {
      id: 'act-chay-river-zipline',
      name: 'Đu dây Zipline & Thám hiểm Hang Tối Sông Chày',
      image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
      price: 450000,
      description: 'Bay đu zipline giữa dòng sông Chày xanh ngọc bích, tắm bùn tự nhiên mát lạnh độc đáo trong Hang Tối.',
      rating: 4.8,
      reviewsCount: '920',
      lat: 17.5742,
      lng: 106.2641,
    },
    {
      id: 'act-sondoong-experience',
      name: 'Hành trình thám hiểm rừng nguyên sinh & Bản Đoòng',
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
      price: 1800000,
      description: 'Tour đi bộ thám hiểm xuyên rừng nguyên sinh Phong Nha, viếng thăm bản đoòng mộc mạc hoang sơ của người dân tộc thiểu số.',
      rating: 4.9,
      reviewsCount: '150',
      lat: 17.5124,
      lng: 106.3125,
    }
  ],
  'phu-yen': [
    {
      id: 'act-ganh-da-dia-tour',
      name: 'Tour tham quan danh thắng Gành Đá Đĩa kì vĩ',
      image: 'https://images.unsplash.com/photo-1623161474966-2615a0c33fb3?auto=format&fit=crop&w=600&q=80',
      price: 120000,
      description: 'Chiêm ngưỡng kiệt tác đá đen bazan hình tổ ong khổng lồ xếp chồng độc đáo bên bờ sóng vỗ rì rào.',
      rating: 4.8,
      reviewsCount: '1.1k',
      lat: 13.3642,
      lng: 109.2941,
    },
    {
      id: 'act-mui-dien-sunrise',
      name: 'Đón bình minh sớm nhất tại Mũi Điện - Bãi Môn',
      image: 'https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?auto=format&fit=crop&w=600&q=80',
      price: 180000,
      description: 'Đứng nơi đón bình minh đầu tiên trên đất liền Việt Nam dưới chân hải đăng trăm tuổi ngắm Bãi Môn thơ mộng.',
      rating: 4.9,
      reviewsCount: '750',
      lat: 12.8941,
      lng: 109.4582,
    },
    {
      id: 'act-nghinh-phong-tour',
      name: 'Check-in tháp Nghinh Phong & tinh hoa văn hóa Phú Yên',
      image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=600&q=80',
      price: 80000,
      description: 'Chiêm ngưỡng công trình biểu tượng lấy cảm hứng từ truyền thuyết Lạc Long Quân - Âu Cơ lộng gió gành đá.',
      rating: 4.7,
      reviewsCount: '580',
      lat: 13.0912,
      lng: 109.3245,
    }
  ],
  'ninh-thuan': [
    {
      id: 'act-vinh-hy-boat',
      name: 'Tàu đáy kính ngắm san hô Vịnh Vĩnh Hy xanh biếc',
      image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80',
      price: 220000,
      description: 'Lướt trên vịnh biển tuyệt sắc bằng tàu đáy kính, ngắm rạn san hô tự nhiên đầy sắc màu và tắm biển bãi Bà Điên.',
      rating: 4.9,
      reviewsCount: '1.3k',
      lat: 11.7182,
      lng: 109.1924,
    },
    {
      id: 'act-poklong-garai',
      name: 'Hành trình di sản Tháp Chàm Po Klong Garai',
      image: 'https://images.unsplash.com/photo-1590372856149-e11154c5e315?auto=format&fit=crop&w=600&q=80',
      price: 100000,
      description: 'Tìm hiểu quần thể tháp gạch Champa hùng vĩ xây dựng thế kỷ XIII-XIV tinh xảo và lễ hội Katê truyền thống.',
      rating: 4.8,
      reviewsCount: '620',
      lat: 11.5982,
      lng: 108.9567,
    },
    {
      id: 'act-ninh-thuan-vineyard',
      name: 'Trải nghiệm hái nho tươi tại vườn nho Ba Mọi',
      image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=600&q=80',
      price: 80000,
      description: 'Thong thả dạo bước dưới giàn nho trĩu quả chín mọng ngọt mát, thưởng thức mứt nho và rượu nho thủ công nguyên chất.',
      rating: 4.7,
      reviewsCount: '490',
      lat: 11.5641,
      lng: 108.9924,
    }
  ],
  'binh-thuan': [
    {
      id: 'act-muine-sand-dunes',
      name: 'Đua xe địa hình ATV chinh phục Đồi Cát Trắng Mũi Né',
      image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=600&q=80',
      price: 350000,
      description: 'Cảm giác cực mạnh khi tự lái mô tô liên hoàn vượt đỉnh đồi cát bao la như sa mạc, chiêm ngưỡng hồ nước ngọt Bàu Trắng.',
      rating: 4.9,
      reviewsCount: '2.1k',
      lat: 11.0624,
      lng: 108.3542,
    },
    {
      id: 'act-fairy-stream',
      name: 'Lội nước dạo bước Suối Tiên Mũi Né thơ mộng',
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
      price: 90000,
      description: 'Đi chân trần dọc dòng suối nhỏ len lỏi qua vách nhũ cát đỏ cam rực rỡ, chiêm ngưỡng kiệt tác gió mài mòn kỳ diệu.',
      rating: 4.8,
      reviewsCount: '1.5k',
      lat: 10.9512,
      lng: 108.2198,
    },
    {
      id: 'act-kega-sunset',
      name: 'Thuyền thúng chinh phục Hải đăng Kê Gà hoàng hôn',
      image: 'https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?auto=format&fit=crop&w=600&q=80',
      price: 150000,
      description: 'Ngồi thuyền thúng của ngư dân địa phương vượt biển lên đảo đá ngắm ngọn hải đăng cổ nhất Việt Nam trong ráng chiều vàng óng.',
      rating: 4.9,
      reviewsCount: '480',
      lat: 10.6982,
      lng: 107.9856,
    }
  ],
  'quang-ngai': [
    {
      id: 'act-ly-son-crater',
      name: 'Khám phá miệng núi lửa Thới Lới - đảo Lý Sơn',
      image: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&w=600&q=80',
      price: 280000,
      description: 'Chinh phục cột cờ Lý Sơn trên đỉnh núi lửa đã tắt hàng triệu năm, thu trọn biển trời bao la hoang sơ.',
      rating: 4.9,
      reviewsCount: '890',
      lat: 15.3941,
      lng: 109.1245,
    },
    {
      id: 'act-garlic-field',
      name: 'Trải nghiệm làm nông dân thu hoạch Tỏi Lý Sơn độc bản',
      image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=600&q=80',
      price: 120000,
      description: 'Trải nghiệm bón cát san hô đỏ cho ruộng tỏi, tự tay thu hoạch sấy khô những củ tỏi cô đơn nức tiếng.',
      rating: 4.8,
      reviewsCount: '340',
      lat: 15.3852,
      lng: 109.1124,
    }
  ],
  'quang-tri': [
    {
      id: 'act-vinh-moc-tunnels',
      name: 'Thám hiểm địa đạo Vịnh Mốc anh dũng trong lòng đất',
      image: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=600&q=80',
      price: 150000,
      description: 'Tham quan hệ thống địa đạo rực lửa chiến tranh dài gần 2km nguyên vẹn hoàn hảo của quân dân Vịnh Mốc dưới độ sâu 20m.',
      rating: 4.8,
      reviewsCount: '410',
      lat: 17.0256,
      lng: 107.1082,
    },
    {
      id: 'act-hien-luong-bridge',
      name: 'Tham quan cụm di tích đôi bờ Hiền Lương - Sông Bến Hải',
      image: 'https://images.unsplash.com/photo-1590372856149-e11154c5e315?auto=format&fit=crop&w=600&q=80',
      price: 100000,
      description: 'Đi bộ qua chiếc cầu Hiền Lương lịch sử chia cắt hai miền Nam - Bắc tại vĩ tuyến 17 hào hùng.',
      rating: 4.7,
      reviewsCount: '320',
      lat: 16.9982,
      lng: 107.0945,
    }
  ],
  'nghe-an': [
    {
      id: 'act-sen-village',
      name: 'Hành trình tìm về quê nội - quê ngoại Bác Hồ tại Làng Sen',
      image: 'https://images.unsplash.com/photo-1540959733332-eab4deceeaf7?auto=format&fit=crop&w=600&q=80',
      price: 120000,
      description: 'Viếng thăm mái nhà tranh vách đất mộc mạc lưu giữ kỉ vật tuổi thơ của lãnh tụ vĩ đại Hồ Chí Minh rợp bóng tre ngà.',
      rating: 4.9,
      reviewsCount: '2.1k',
      lat: 18.6754,
      lng: 105.5682,
    },
    {
      id: 'act-cualo-snorkeling',
      name: 'Tour lặn ngắm san hô & câu mực đêm Đảo Ngư Cửa Lò',
      image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
      price: 350000,
      description: 'Trải nghiệm lênh đênh trên thuyền thúng câu mực nhảy ban đêm và ngắm rạn san hô hoang dã quanh Đảo Ngư.',
      rating: 4.7,
      reviewsCount: '410',
      lat: 18.8214,
      lng: 105.7485,
    }
  ]
};

export const vehicles: Vehicle[] = [
  {
    id: 'veh-sirius',
    name: 'Yamaha Sirius 110cc (Tiết kiệm xăng)',
    type: 'motorbike',
    pricePerDay: 120000,
    image: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=400&q=80',
    specs: 'Xe số dẻo dai, tiết kiệm xăng vượt trội, phù hợp vượt đồi lướt thung lũng.',
    rating: 4.7
  },
  {
    id: 'veh-vision',
    name: 'Honda Vision 110cc Smartkey',
    type: 'motorbike',
    pricePerDay: 150000,
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=400&q=80',
    specs: 'Khóa thông minh, cốp xe rộng rãi, lái nhẹ nhàng êm ái trên các nẻo đường đô thị.',
    rating: 4.8
  },
  {
    id: 'veh-lead',
    name: 'Honda Lead 125cc Cốp cực rộng',
    type: 'motorbike',
    pricePerDay: 170000,
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=400&q=80',
    specs: 'Cốp xe siêu rộng 37 lít chứa được 2 nón bảo hiểm và nhiều hành lý lặt vặt.',
    rating: 4.8
  },
  {
    id: 'veh-exciter',
    name: 'Yamaha Exciter 150cc Côn Tay',
    type: 'motorbike',
    pricePerDay: 200000,
    image: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=400&q=80',
    specs: 'Động cơ côn tay thể thao mạnh mẽ, bốc lửa, phù hợp chinh phục đèo Hải Vân kỳ vĩ.',
    rating: 4.9
  },
  {
    id: 'veh-sh',
    name: 'Honda SH Premium 150cc',
    type: 'motorbike',
    pricePerDay: 250000,
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=400&q=80',
    specs: 'Đẳng cấp lịch lãm phong trần, động cơ cực mạnh phù hợp hành trình đường dài liên tỉnh.',
    rating: 4.9
  },
  {
    id: 'veh-airblade',
    name: 'Honda Air Blade 125cc Thể Thao',
    type: 'motorbike',
    pricePerDay: 180000,
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=400&q=80',
    specs: 'Động cơ eSP+ tiên tiến, vận hành mạnh mẽ khỏe khoắn, thiết kế nam tính hiện đại.',
    rating: 4.8
  },
  {
    id: 'veh-vespa',
    name: 'Vespa Primavera 125cc Thời Trang',
    type: 'motorbike',
    pricePerDay: 300000,
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=400&q=80',
    specs: 'Phong cách Ý cổ điển quyến rũ thanh lịch, màu sơn thời trang tôn dáng chụp hình.',
    rating: 4.9
  },
  {
    id: 'veh-raider',
    name: 'Suzuki Raider 150cc Underbone',
    type: 'motorbike',
    pricePerDay: 220000,
    image: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=400&q=80',
    specs: 'Kiểu dáng hyper-underbone siêu ngầu, tốc độ bứt phá cực nhanh cho bạn trẻ mê phượt.',
    rating: 4.7
  },
  {
    id: 'veh-giant-bike',
    name: 'Xe đạp địa hình Giant ATX',
    type: 'motorbike',
    pricePerDay: 80000,
    image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=400&q=80',
    specs: 'Khung nhôm siêu nhẹ Aluxx, phuộc nhún êm ái thích hợp đạp thong dong khám phá phố cổ.',
    rating: 4.8
  },
  {
    id: 'veh-i10',
    name: 'Hyundai i10 Hatchback (Tự Lái)',
    type: 'car',
    pricePerDay: 750000,
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=400&q=80',
    specs: 'Xe số tự động nhỏ gọn, cực kỳ linh hoạt luồn lách qua các ngõ hẻm đô thị.',
    rating: 4.7
  },
  {
    id: 'veh-accent',
    name: 'Hyundai Accent Sedan (Tự Lái)',
    type: 'car',
    pricePerDay: 900000,
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=400&q=80',
    specs: 'Sedan 5 chỗ thời trang hiện đại, có trang bị cảm biến lùi, bluetooth kết nối rảnh tay.',
    rating: 4.8
  },
  {
    id: 'veh-vios',
    name: 'Toyota Vios 5 Chỗ (Có tài xế riêng)',
    type: 'car',
    pricePerDay: 1000000,
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=400&q=80',
    specs: 'Xe Sedan mát lạnh sạch sẽ, tài xế cư xử lịch sự am tường lối ngõ lịch trình linh hoạt.',
    rating: 4.8
  },
  {
    id: 'veh-xpander-self',
    name: 'Mitsubishi Xpander 7 Chỗ (Tự Lái)',
    type: 'car',
    pricePerDay: 1100000,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=400&q=80',
    specs: 'Mẫu xe 7 chỗ tự lái quốc dân rộng rãi, máy lạnh buốt sâu, ghế da êm ái cho cả gia đình.',
    rating: 4.9
  },
  {
    id: 'veh-xpander',
    name: 'Mitsubishi Xpander 7 Chỗ (Có tài xế)',
    type: 'car',
    pricePerDay: 1300000,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=400&q=80',
    specs: 'Nội thất cực rộng cho đại gia đình, có gá nóc hành lý cồng kềnh đầy tiện nghi.',
    rating: 4.9
  },
  {
    id: 'veh-fortuner',
    name: 'Toyota Fortuner SUV 7 Chỗ (Tự Lái)',
    type: 'car',
    pricePerDay: 1400000,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=400&q=80',
    specs: 'SUV 7 chỗ gầm cao, máy dầu bền bỉ tiết kiệm, vượt mọi địa hình đồi núi mượt mà.',
    rating: 4.9
  },
  {
    id: 'veh-vf5',
    name: 'VinFast VF5 Electric SUV (Tự Lái)',
    type: 'car',
    pricePerDay: 800000,
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=400&q=80',
    specs: 'Xe điện đô thị thông minh, bảo vệ môi trường, vận hành cực kỳ êm ái và bốc.',
    rating: 4.8
  },
  {
    id: 'veh-vf8',
    name: 'VinFast VF8 Luxury Electric SUV (Tự Lái)',
    type: 'car',
    pricePerDay: 1600000,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=400&q=80',
    specs: 'SUV điện hạng sang thông minh đẳng cấp, hệ thống ADAS lái tự động tiện nghi bậc nhất.',
    rating: 5.0
  },
  {
    id: 'veh-camry',
    name: 'Toyota Camry Sedan Hạng Sang (Tự Lái)',
    type: 'car',
    pricePerDay: 1800000,
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=400&q=80',
    specs: 'Sedan hạng sang lịch lãm chuẩn mực, mang đến sự đẳng cấp, tĩnh lặng tuyệt đối cho quý doanh nhân.',
    rating: 4.9
  },
  {
    id: 'veh-transit',
    name: 'Ford Transit 16 Chỗ (Có tài xế)',
    type: 'car',
    pricePerDay: 1800000,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=400&q=80',
    specs: 'Xe 16 chỗ đời mới mát mẻ rộng rãi, tài xế đón tiễn tận tình đúng giờ suốt hành trình.',
    rating: 4.8
  },
  {
    id: 'veh-solati-limo',
    name: 'Hyundai Solati Limousine 9 Chỗ VIP (Có tài)',
    type: 'car',
    pricePerDay: 2800000,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=400&q=80',
    specs: 'Nội thất khoang thương gia siêu sang, ghế massage bọc da cao cấp, sạc USB, tủ lạnh mini tiện nghi.',
    rating: 5.0
  },
  {
    id: 'veh-vespa-lx',
    name: 'Vespa LX 125cc Cổ Điển',
    type: 'motorbike',
    pricePerDay: 200000,
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=400&q=80',
    specs: 'Dòng xe Vespa Ý thời trang thanh lịch cổ điển, cực kỳ tôn dáng khi chụp ảnh check-in kỷ niệm tại phố cổ Hội An.',
    rating: 4.8
  },
  {
    id: 'veh-xe-om-dien',
    name: 'Xe điện Lihaze mini dễ thương',
    type: 'motorbike',
    pricePerDay: 130000,
    image: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=400&q=80',
    specs: 'Chạy điện êm ái bảo vệ môi trường, thiết kế mini dễ thương, giỏ xe lớn tiện ích, thích hợp cho các bạn nữ dạo mát nhẹ nhàng.',
    rating: 4.7
  },
  {
    id: 'veh-kia-carnival',
    name: 'Kia Carnival Signature 8 Chỗ (Có tài xế)',
    type: 'car',
    pricePerDay: 2200000,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=400&q=80',
    specs: 'Chuyên cơ mặt đất 8 chỗ siêu rộng rãi đời mới nhất, ghế thương gia bọc da cao cấp ngả lưng bọc da êm ái phù hợp đón tiễn sân bay Vip.',
    rating: 5.0
  },
  {
    id: 'veh-vinfast-vfe34',
    name: 'VinFast VF e34 SUV Điện (Tự Lái)',
    type: 'car',
    pricePerDay: 700000,
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=400&q=80',
    specs: 'SUV điện thông minh 5 chỗ rộng rãi mát mẻ, vận hành êm ru không tiếng ồn cực kỳ tiết kiệm chi phí nhiên liệu sạc pin.',
    rating: 4.8
  },
  {
    id: 'veh-giant-ebike',
    name: 'Xe đạp điện Giant E-Bike thông minh',
    type: 'motorbike',
    pricePerDay: 120000,
    image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=400&q=80',
    specs: 'Xe trợ lực điện Giant nhập khẩu chính hãng, pin bền bỉ lâu bền giúp lướt êm ái xuyên phố cổ mà không lo tốn sức.',
    rating: 4.8
  }
];

export const reviews: Review[] = [
  {
    id: 'rev-1',
    author: 'Nguyễn Minh Hải',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=100&q=80',
    rating: 5,
    date: '2026-06-15',
    comment: 'Tôi vô cùng ấn tượng với tính năng Lên lịch trình tự động bằng AI! Chỉ cần nhập chi phí và sở thích, hệ thống đã tối ưu toàn bộ từ khách sạn, xe máy đến thứ tự tham quan Hội An - Đà Nẵng cực kỳ mượt mà, giúp gia đình tiết kiệm được 15% tổng hóa đơn!',
    locale: 'vi'
  },
  {
    id: 'rev-2',
    author: 'Sarah Jenkins',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80',
    rating: 5,
    date: '2026-06-12',
    comment: 'The booking process was flawless! Recommended hotels and localized tours in Hoi An matched perfectly with Klook levels of detail. Highly secure credit card processing with instant digital receipt makes them stand out!',
    locale: 'en'
  },
  {
    id: 'rev-3',
    author: 'Trần Vũ Hoàng',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=100&q=80',
    rating: 5,
    date: '2026-06-08',
    comment: 'Tuyệt đỉnh! Dễ dàng đổi qua lại ngôn ngữ. Được thuê xe máy Sirius lướt thong thả từ Đà Nẵng ra Hội An theo định vị bản đồ thời gian thực tích hợp bên trong cực kì an toàn và chính xác.',
    locale: 'vi'
  }
];

export const dictionaries = {
  vi: {
    welcome: 'Chào mừng bạn đến với',
    title: 'VietCharm - Du lịch lữ hành & Đặt tour Miền Trung',
    promo: 'Khuyến mãi',
    partner: 'Hợp tác với chúng tôi',
    support: 'Hỗ trợ',
    recent: 'Xem gần đây',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    homeTitle: 'Khám phá di sản Việt cùng VietCharm',
    homeSub: 'Hệ thống đặt tour, khách sạn và phương tiện lữ hành trực tuyến an toàn, linh hoạt hàng đầu từ ba miền Tổ Quốc.',
    selectRegion: 'Chọn Vùng Miền Bạn Muốn Khám Phá',
    north: 'Miền Bắc',
    central: 'Miền Trung',
    south: 'Miền Nam',
    devStatus: 'Hệ thống đang phát triển',
    devBody: 'Rất tiếc! Hệ thống đặt trực tuyến cho khu vực này đang được chúng tôi cấu trúc cơ sở dữ liệu và liên kết đối tác. Vui lòng quay lại sau ít lâu hoặc thử ngay khu vực Miền Trung!',
    backToHome: 'Quay lại trang chủ',
    exploreHoiAn: 'Khám phá Hội An',
    hotelsName: 'Khách sạn',
    carsName: 'Thuê xe',
    experiencesName: 'Hoạt động & Vui chơi',
    toursName: 'Tour du lịch',
    more: 'Xem thêm',
    exploreNow: 'KHÁM PHÁ NGAY',
    heroSearchTitle: 'Bạn muốn tìm gì?',
    searchPlaceholder: 'Khách sạn, địa điểm, hoạt động...',
    checkIn: 'Nhận phòng',
    checkOut: 'Trả phòng',
    guestsNum: 'Số khách',
    guestRoom: '1 Khách, 1 Phòng',
    searchBtn: 'Tìm kiếm',
    uspsTitle1: 'Trải nghiệm địa phương',
    uspsSub1: 'Khám phá Hội An theo cách riêng cùng người bản địa mộc mạc.',
    uspsTitle2: 'Giá tốt nhất',
    uspsSub2: 'Cam kết giá tốt nhất với nhiều combo ưu đãi độc quyền 15-20%.',
    uspsTitle3: 'Đáng tin cậy',
    uspsSub3: 'Nhà cung cấp uy tín hàng đầu, cổng thanh toán bảo mật đa lớp SSL.',
    uspsTitle4: 'Hỗ trợ 24/7',
    uspsSub4: 'Đội ngũ tư vấn túc trực sẵn sàng gỡ rối khó khăn mọi lúc nơi.',
    featuredSpots: 'Điểm đến nổi bật',
    spotSubtitle: 'Những địa điểm không thể bỏ lỡ khi ghé thăm Hội An & Miền Trung',
    lovedHotels: 'Khách sạn',
    hotelSubtitle: 'Nơi lưu giữ kỉ niệm, là chỗ nghỉ ngơi lý tưởng và bình yên cho kỳ nghỉ của bạn',
    perNight: '/đêm',
    activitiesTitle: 'Hoạt động & trải nghiệm',
    activitiesSubtitle: 'Trải nghiệm văn hóa, ẩm thực đầy sinh động lôi cuốn',
    promoBannerTitle: 'Ưu đãi độc quyền dành cho bạn!',
    promoBannerSub: 'Đăng ký nhập email ngay để nhận ngay voucher giảm 10% cho dịch vụ đặt đầu tiên từ VietCharm.',
    subPlaceholder: 'Nhập email của bạn',
    subscribe: 'Đăng ký liền tay',
    aiPilotTitle: 'AI Co-Pilot: Trợ Lý Lịch Trình & Tối Ưu Chi Phí',
    aiPilotSub: 'Chức năng đột phá giúp bạn tìm kiếm, lập lộ trình chi tiết và bóc tách gói combo tiết kiệm lên tới 30%!',
    askAIPlaceholder: 'Nhập yêu cầu (ví dụ: Tôi có 4 triệu, muốn du lịch cặp đôi 3 ngày 2 đêm ở Hội An...)',
    mapTitle: 'Trực Quan Hóa Lột Trình & Bản Đồ Chỉ Đường Thời Gian Thực',
    securePayment: 'Thanh toán bảo mật',
    paymentSuccess: 'Giao dịch thành công!',
    eTicket: 'Thẻ Vé Điện Tử VietCharm',
    provinceSelect: 'Chọn Thành Phố Bạn Khám Phá',
    visitOtherProvinces: 'Gần Hội An còn có...',
    allInOneCombo: 'Đặt Trọn Gói Combo Tiết Kiệm IPP',
    rentVehicles: 'Cho Thuê Phương Tiện Tự Lái',
    addSelection: 'Thêm vào hành trình',
    removeSelection: 'Bỏ chọn',
    totalEstimated: 'Tổng hóa đơn ước tính',
  },
  en: {
    welcome: 'Welcome to',
    title: 'VietCharm - Central Vietnam Travel & Tour Booking Portal',
    promo: 'Promotions',
    partner: 'Partner with us',
    support: 'Support',
    recent: 'Recently viewed',
    login: 'Login',
    register: 'Register',
    homeTitle: 'Explore Vietnamese Heritage with VietCharm',
    homeSub: 'Leading secure online booking portal for tours, hotels, and rentals across scenic historical regions.',
    selectRegion: 'Select the Region You Wish to Explore',
    north: 'Northern Region',
    central: 'Central Region',
    south: 'Southern Region',
    devStatus: 'Under Active Development',
    devBody: 'Apologies! Active booking setups for this region are undergoing deep database indexing and local vendor integrations. Try Central region right now!',
    backToHome: 'Back to Home',
    exploreHoiAn: 'Explore Hoi An',
    hotelsName: 'Hotels',
    carsName: 'Rentals',
    experiencesName: 'Activities & Fun',
    toursName: 'Vaction Tours',
    more: 'More',
    exploreNow: 'EXPLORE NOW',
    heroSearchTitle: 'What do you desire?',
    searchPlaceholder: 'Hotels, locations, events, tours...',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
    guestsNum: 'Guests',
    guestRoom: '1 Guest, 1 Room',
    searchBtn: 'Search Now',
    uspsTitle1: 'Local Experiences',
    uspsSub1: 'Venture into real Vietnam through guidance of friendly locals.',
    uspsTitle2: 'Cost-Effective Deals',
    uspsSub2: 'We commit to best price guarantee and premium 15-20% bundling savers.',
    uspsTitle3: 'Trusted & Certified',
    uspsSub3: 'Leading network providers with SSL multi-shield payment processing.',
    uspsTitle4: '24/7 Desk Help',
    uspsSub4: 'A dedicated representative is always available to assist on-the-go.',
    featuredSpots: 'Featured Attractions',
    spotSubtitle: 'Must-visit scenic locations during your majestic tour',
    lovedHotels: 'Most Loved Accommodations',
    hotelSubtitle: 'Perfect peaceful sanctuaries to unwind your holiday',
    perNight: '/night',
    activitiesTitle: 'Activities & Local Heritage',
    activitiesSubtitle: 'Vibrant local culinary and cultural immersion workshops',
    promoBannerTitle: 'Exclusive Privileges For You!',
    promoBannerSub: 'Register your email to instantly receive a 10% voucher for your first booking.',
    subPlaceholder: 'Enter your email',
    subscribe: 'Subscribe Now',
    aiPilotTitle: 'AI Co-Pilot: Itinerary & Budget Energy Saver',
    aiPilotSub: 'Breakthrough automation mapping out deep-dive schedules and up to 30% saving combos.',
    askAIPlaceholder: 'Enter prompt (e.g. Couples retreat for 3 days 2 nights with 200 USD budget in Hue and Hoi An)',
    mapTitle: 'Real-time Live Navigation & Route Visualization Map',
    securePayment: 'Secure Encrypted Checkout',
    paymentSuccess: 'Transaction Certified Secure!',
    eTicket: 'VietCharm Verified E-Ticket',
    provinceSelect: 'Select Scenic City',
    visitOtherProvinces: 'Explore Surrounding Provinces',
    allInOneCombo: 'Instant Combo Bundle & Saver',
    rentVehicles: 'Private Multi-Vehicle Rental',
    addSelection: 'Add to Bundle',
    removeSelection: 'Remove item',
    totalEstimated: 'Estimated total balance',
  }
};
